// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tijpnmrurgydcqczacel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpanBubXJ1cmd5ZGNxY3phY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzUwOTEsImV4cCI6MjA2NjExMTA5MX0.3Xt2YSpEiYu4cZybujIl-ivXOXMc74_3dr1EH_OggQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);